// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/fsdevblog/shorturl/internal/models"
	services "github.com/fsdevblog/shorturl/internal/services"
	gomock "github.com/golang/mock/gomock"
)

// MockConnectionChecker is a mock of ConnectionChecker interface.
type MockConnectionChecker struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionCheckerMockRecorder
}

// MockConnectionCheckerMockRecorder is the mock recorder for MockConnectionChecker.
type MockConnectionCheckerMockRecorder struct {
	mock *MockConnectionChecker
}

// NewMockConnectionChecker creates a new mock instance.
func NewMockConnectionChecker(ctrl *gomock.Controller) *MockConnectionChecker {
	mock := &MockConnectionChecker{ctrl: ctrl}
	mock.recorder = &MockConnectionCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionChecker) EXPECT() *MockConnectionCheckerMockRecorder {
	return m.recorder
}

// CheckConnection mocks base method.
func (m *MockConnectionChecker) CheckConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckConnection indicates an expected call of CheckConnection.
func (mr *MockConnectionCheckerMockRecorder) CheckConnection(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConnection", reflect.TypeOf((*MockConnectionChecker)(nil).CheckConnection), ctx)
}

// MockURLProvider is a mock of URLProvider interface.
type MockURLProvider struct {
	ctrl     *gomock.Controller
	recorder *MockURLProviderMockRecorder
}

// MockURLProviderMockRecorder is the mock recorder for MockURLProvider.
type MockURLProviderMockRecorder struct {
	mock *MockURLProvider
}

// NewMockURLProvider creates a new mock instance.
func NewMockURLProvider(ctrl *gomock.Controller) *MockURLProvider {
	mock := &MockURLProvider{ctrl: ctrl}
	mock.recorder = &MockURLProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLProvider) EXPECT() *MockURLProviderMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockURLProvider) BatchCreate(ctx context.Context, visitorUUID string, rawURLs []string) (*services.BatchCreateShortURLsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, visitorUUID, rawURLs)
	ret0, _ := ret[0].(*services.BatchCreateShortURLsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockURLProviderMockRecorder) BatchCreate(ctx, visitorUUID, rawURLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockURLProvider)(nil).BatchCreate), ctx, visitorUUID, rawURLs)
}

// Create mocks base method.
func (m *MockURLProvider) Create(ctx context.Context, visitorUUID, rawURL string) (*models.URL, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, visitorUUID, rawURL)
	ret0, _ := ret[0].(*models.URL)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockURLProviderMockRecorder) Create(ctx, visitorUUID, rawURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockURLProvider)(nil).Create), ctx, visitorUUID, rawURL)
}

// GetAllByVisitorUUID mocks base method.
func (m *MockURLProvider) GetAllByVisitorUUID(ctx context.Context, visitorUUID string) ([]models.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByVisitorUUID", ctx, visitorUUID)
	ret0, _ := ret[0].([]models.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByVisitorUUID indicates an expected call of GetAllByVisitorUUID.
func (mr *MockURLProviderMockRecorder) GetAllByVisitorUUID(ctx, visitorUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByVisitorUUID", reflect.TypeOf((*MockURLProvider)(nil).GetAllByVisitorUUID), ctx, visitorUUID)
}

// GetByShortIdentifier mocks base method.
func (m *MockURLProvider) GetByShortIdentifier(ctx context.Context, shortID string) (*models.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShortIdentifier", ctx, shortID)
	ret0, _ := ret[0].(*models.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShortIdentifier indicates an expected call of GetByShortIdentifier.
func (mr *MockURLProviderMockRecorder) GetByShortIdentifier(ctx, shortID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShortIdentifier", reflect.TypeOf((*MockURLProvider)(nil).GetByShortIdentifier), ctx, shortID)
}

// GetByURL mocks base method.
func (m *MockURLProvider) GetByURL(ctx context.Context, rawURL string) (*models.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByURL", ctx, rawURL)
	ret0, _ := ret[0].(*models.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByURL indicates an expected call of GetByURL.
func (mr *MockURLProviderMockRecorder) GetByURL(ctx, rawURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByURL", reflect.TypeOf((*MockURLProvider)(nil).GetByURL), ctx, rawURL)
}

// MarkAsDeleted mocks base method.
func (m *MockURLProvider) MarkAsDeleted(ctx context.Context, shortIDs []string, visitorUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsDeleted", ctx, shortIDs, visitorUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsDeleted indicates an expected call of MarkAsDeleted.
func (mr *MockURLProviderMockRecorder) MarkAsDeleted(ctx, shortIDs, visitorUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsDeleted", reflect.TypeOf((*MockURLProvider)(nil).MarkAsDeleted), ctx, shortIDs, visitorUUID)
}

// MockStatsProvider is a mock of StatsProvider interface.
type MockStatsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStatsProviderMockRecorder
}

// MockStatsProviderMockRecorder is the mock recorder for MockStatsProvider.
type MockStatsProviderMockRecorder struct {
	mock *MockStatsProvider
}

// NewMockStatsProvider creates a new mock instance.
func NewMockStatsProvider(ctrl *gomock.Controller) *MockStatsProvider {
	mock := &MockStatsProvider{ctrl: ctrl}
	mock.recorder = &MockStatsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsProvider) EXPECT() *MockStatsProviderMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsProvider) GetStats(ctx context.Context) (*services.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*services.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsProviderMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsProvider)(nil).GetStats), ctx)
}
