services:
  postgres:
    image: postgres:17
    container_name: study1-pg
    env_file:
      - ./.env
    ports:
      - "5435:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/sql:/app/sql
volumes:
  postgres_data:
