// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: internal/transport/grpc/proto/shorturl.proto

package shorturl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	VisitorUUID   string                 `protobuf:"bytes,2,opt,name=visitorUUID,proto3" json:"visitorUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateShortURLRequest) GetVisitorUUID() string {
	if x != nil {
		return x.VisitorUUID
	}
	return ""
}

type CreateShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLResponse) Reset() {
	*x = CreateShortURLResponse{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLResponse) ProtoMessage() {}

func (x *CreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type BatchCreateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateParams) Reset() {
	*x = BatchCreateParams{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateParams) ProtoMessage() {}

func (x *BatchCreateParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateParams.ProtoReflect.Descriptor instead.
func (*BatchCreateParams) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *BatchCreateParams) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchCreateParams) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchCreateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateResult) Reset() {
	*x = BatchCreateResult{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateResult) ProtoMessage() {}

func (x *BatchCreateResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateResult.ProtoReflect.Descriptor instead.
func (*BatchCreateResult) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCreateResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchCreateResult) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *BatchCreateResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BatchCreateParams   `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRequest) Reset() {
	*x = BatchCreateRequest{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRequest) ProtoMessage() {}

func (x *BatchCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateRequest) GetUrls() []*BatchCreateParams {
	if x != nil {
		return x.Urls
	}
	return nil
}

type BatchCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*BatchCreateResult   `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateResponse) Reset() {
	*x = BatchCreateResponse{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateResponse) ProtoMessage() {}

func (x *BatchCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{5}
}

func (x *BatchCreateResponse) GetResult() []*BatchCreateResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserURLsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{7}
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{8}
}

type UserUrls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUrls) Reset() {
	*x = UserUrls{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrls) ProtoMessage() {}

func (x *UserUrls) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrls.ProtoReflect.Descriptor instead.
func (*UserUrls) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{9}
}

func (x *UserUrls) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserUrls) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type UserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserUrls            `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_shorturl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLsResponse.ProtoReflect.Descriptor instead.
func (*UserURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP(), []int{10}
}

func (x *UserURLsResponse) GetUrls() []*UserUrls {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_internal_transport_grpc_proto_shorturl_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_proto_shorturl_proto_rawDesc = "" +
	"\n" +
	",internal/transport/grpc/proto/shorturl.proto\x12\bshorturl\"K\n" +
	"\x15CreateShortURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vvisitorUUID\x18\x02 \x01(\tR\vvisitorUUID\"0\n" +
	"\x16CreateShortURLResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"]\n" +
	"\x11BatchCreateParams\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"m\n" +
	"\x11BatchCreateResult\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"E\n" +
	"\x12BatchCreateRequest\x12/\n" +
	"\x04urls\x18\x01 \x03(\v2\x1b.shorturl.BatchCreateParamsR\x04urls\"J\n" +
	"\x13BatchCreateResponse\x123\n" +
	"\x06result\x18\x01 \x03(\v2\x1b.shorturl.BatchCreateResultR\x06result\")\n" +
	"\x15DeleteUserURLsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x0f\n" +
	"\rEmptyResponse\"\x0e\n" +
	"\fEmptyRequest\"J\n" +
	"\bUserUrls\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\":\n" +
	"\x10UserURLsResponse\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.shorturl.UserUrlsR\x04urls2\xb7\x02\n" +
	"\bShortURL\x12S\n" +
	"\x0eCreateShortURL\x12\x1f.shorturl.CreateShortURLRequest\x1a .shorturl.CreateShortURLResponse\x12J\n" +
	"\vBatchCreate\x12\x1c.shorturl.BatchCreateRequest\x1a\x1d.shorturl.BatchCreateResponse\x12J\n" +
	"\x0eDeleteUserURLs\x12\x1f.shorturl.DeleteUserURLsRequest\x1a\x17.shorturl.EmptyResponse\x12>\n" +
	"\bUserURLs\x12\x16.shorturl.EmptyRequest\x1a\x1a.shorturl.UserURLsResponseBFZDgithub.com/fsdevblog/shorturl/internal/transport/grpc/proto;shorturlb\x06proto3"

var (
	file_internal_transport_grpc_proto_shorturl_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_proto_shorturl_proto_rawDescData []byte
)

func file_internal_transport_grpc_proto_shorturl_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_proto_shorturl_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_proto_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_shorturl_proto_rawDesc), len(file_internal_transport_grpc_proto_shorturl_proto_rawDesc)))
	})
	return file_internal_transport_grpc_proto_shorturl_proto_rawDescData
}

var file_internal_transport_grpc_proto_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_transport_grpc_proto_shorturl_proto_goTypes = []any{
	(*CreateShortURLRequest)(nil),  // 0: shorturl.CreateShortURLRequest
	(*CreateShortURLResponse)(nil), // 1: shorturl.CreateShortURLResponse
	(*BatchCreateParams)(nil),      // 2: shorturl.BatchCreateParams
	(*BatchCreateResult)(nil),      // 3: shorturl.BatchCreateResult
	(*BatchCreateRequest)(nil),     // 4: shorturl.BatchCreateRequest
	(*BatchCreateResponse)(nil),    // 5: shorturl.BatchCreateResponse
	(*DeleteUserURLsRequest)(nil),  // 6: shorturl.DeleteUserURLsRequest
	(*EmptyResponse)(nil),          // 7: shorturl.EmptyResponse
	(*EmptyRequest)(nil),           // 8: shorturl.EmptyRequest
	(*UserUrls)(nil),               // 9: shorturl.UserUrls
	(*UserURLsResponse)(nil),       // 10: shorturl.UserURLsResponse
}
var file_internal_transport_grpc_proto_shorturl_proto_depIdxs = []int32{
	2,  // 0: shorturl.BatchCreateRequest.urls:type_name -> shorturl.BatchCreateParams
	3,  // 1: shorturl.BatchCreateResponse.result:type_name -> shorturl.BatchCreateResult
	9,  // 2: shorturl.UserURLsResponse.urls:type_name -> shorturl.UserUrls
	0,  // 3: shorturl.ShortURL.CreateShortURL:input_type -> shorturl.CreateShortURLRequest
	4,  // 4: shorturl.ShortURL.BatchCreate:input_type -> shorturl.BatchCreateRequest
	6,  // 5: shorturl.ShortURL.DeleteUserURLs:input_type -> shorturl.DeleteUserURLsRequest
	8,  // 6: shorturl.ShortURL.UserURLs:input_type -> shorturl.EmptyRequest
	1,  // 7: shorturl.ShortURL.CreateShortURL:output_type -> shorturl.CreateShortURLResponse
	5,  // 8: shorturl.ShortURL.BatchCreate:output_type -> shorturl.BatchCreateResponse
	7,  // 9: shorturl.ShortURL.DeleteUserURLs:output_type -> shorturl.EmptyResponse
	10, // 10: shorturl.ShortURL.UserURLs:output_type -> shorturl.UserURLsResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_proto_shorturl_proto_init() }
func file_internal_transport_grpc_proto_shorturl_proto_init() {
	if File_internal_transport_grpc_proto_shorturl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_shorturl_proto_rawDesc), len(file_internal_transport_grpc_proto_shorturl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_proto_shorturl_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_proto_shorturl_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_proto_shorturl_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_proto_shorturl_proto = out.File
	file_internal_transport_grpc_proto_shorturl_proto_goTypes = nil
	file_internal_transport_grpc_proto_shorturl_proto_depIdxs = nil
}
